project:
  type: website
  output-dir: docs
  resources:
    - "games/**"

website:
  title: "Fras Green"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/Fraser-Greenlee
      - icon: twitter
        href: https://twitter.com/FraserGreenlee
format:
  html:
    theme: cosmo
    css: styles.css



