project:
  type: website
  output-dir: docs

website:
  title: "Fras Green"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/FraserGreenlee
      - icon: twitter
        href: https://twitter.com/FraserGreenlee
format:
  html:
    theme: cosmo
    css: styles.css



